POST  http://localhost:4500/users/register
Content-Type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "email":"muriithikiamad1+456@gmail.com" ,
    "role":"customer",    
    "phoneNumber":"03655644567",
    "password":"password12344"
}


###
DELETE  http://localhost:4500/users/deactivateUser/78386d78-0b45-47b4-9ae0-13a26052f6b2
Content-Type: application/json

###
GET  http://localhost:4500/users/allCustomers
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NWQ5YjM5ZC03NWI2LTQ0OTYtYTllZC0zOTk2MDQ2OTYwNmQiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6Im11cmlpdGhpa2lhbWFkMSs0NTZAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwicGhvbmVOdW1iZXIiOiIwMzY1NTY0NDU2NyIsInJlZ2lzdGVyRGF0ZSI6IjIwMjQtMDUtMDdUMDA6MDA6MDAuMDAwWiIsImlhdCI6MTcxNTA4ODExOSwiZXhwIjoxNzE1MzQ3MzE5fQ.QjFsga72-jXQyXYzj8agYP-Xv1Uy9bboXhSUej-wQwI

###
GET  http://localhost:4500/users/customer/78386d78-0b45-47b4-9ae0-13a26052f6b2
Content-Type: application/json

###
###
GET  http://localhost:4500/users/allCouriers
Content-Type: application/json


###
GET  http://localhost:4500/users/courier
Content-Type: application/json


###    Inventory Routes
POST http://localhost:4500/inventory/addProduct
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ODM4NmQ3OC0wYjQ1LTQ3YjQtOWFlMC0xM2EyNjA1MmY2YjIiLCJmaXJzdE5hbWUiOiJEYXZpZCIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJtdXJpaXRoaWtpYW1hZDErNDIzQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInBob25lTnVtYmVyIjoiMDM2NTU2NDQ1NjciLCJyZWdpc3RlckRhdGUiOiIyMDI0LTA0LTI0VDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3MTQ0Njc0NTEsImV4cCI6MTcxNDcyNjY1MX0.v0yyDQ2EtApSFVZwD6Lo1x9YxCTVk_aKJmplhiFmlog


{
    "image":"wertyuiertyuidfgh",
    "productName":"Juice",
    "description":"Pineapple",
    "category":"Beverage",
    "quantity":"10",
    "currentPrice":"4", 
    "formerPrice":"4"
}


###


GET  http://localhost:4500/inventory/allProducts
Content-Type: application/json


###
GET  http://localhost:4500/inventory/product/f0619109-b60b-4714-93ed-fc07895ec3da
Content-Type: application/json


###
DELETE   http://localhost:4500/inventory/deleteProduct/f0619109-b60b-4714-93ed-fc07895ec3da
Content-Type: application/json


### Cart Routes
POST http://localhost:4500/cart/addToCart
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Njg1MWZlZi1iMzY5LTQyOTMtOThmYS1iZTFhMWViYzE5ZDQiLCJmaXJzdE5hbWUiOiJKb2huIiwibGFzdE5hbWUiOiJEb2UiLCJlbWFpbCI6Im11cmlpdGhpa2lhbWFkMSs0NTZAZ21haWwuY29tIiwicm9sZSI6ImN1c3RvbWVyIiwicGhvbmVOdW1iZXIiOiIwMzY1NTY0NDU2NyIsInJlZ2lzdGVyRGF0ZSI6IjIwMjQtMDQtMzBUMDA6MDA6MDAuMDAwWiIsImlhdCI6MTcxNDQ2OTM4OCwiZXhwIjoxNzE0NzI4NTg4fQ.ZncT6r2RhPz7WrlRXCbLKnlUZ_pNTlSzjMFBASumQUI

{
    "productId":"0480fb2f-e350-49f5-9c96-bf52c5ee6ec6",
    "userId":"56851fef-b369-4293-98fa-be1a1ebc19d4",
    "quantity":"8"
}


### 
DELETE  http://localhost:4500/cart/removeItemFromCart/f0619109-b60b-4714-93ed-fc07895ec3da
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ODM4NmQ3OC0wYjQ1LTQ3YjQtOWFlMC0xM2EyNjA1MmY2YjIiLCJmaXJzdE5hbWUiOiJEYXZpZCIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJtdXJpaXRoaWtpYW1hZDErNDIzQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInBob25lTnVtYmVyIjoiMDM2NTU2NDQ1NjciLCJyZWdpc3RlckRhdGUiOiIyMDI0LTA0LTI0VDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3MTQxMTc0MDksImV4cCI6MTcxNDM3NjYwOX0.Su08LNbdg-99OihBahfGj8p8asl5UQZGXJ2lpjbsYWs


###
GET http://localhost:4500/cart/cartItems
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ODM4NmQ3OC0wYjQ1LTQ3YjQtOWFlMC0xM2EyNjA1MmY2YjIiLCJmaXJzdE5hbWUiOiJEYXZpZCIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJtdXJpaXRoaWtpYW1hZDErNDIzQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInBob25lTnVtYmVyIjoiMDM2NTU2NDQ1NjciLCJyZWdpc3RlckRhdGUiOiIyMDI0LTA0LTI0VDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3MTQ0Njc0NTEsImV4cCI6MTcxNDcyNjY1MX0.v0yyDQ2EtApSFVZwD6Lo1x9YxCTVk_aKJmplhiFmlog

{
    "userId":"56851fef-b369-4293-98fa-be1a1ebc19d4"
}

###

