POST  http://localhost:4500/users/register
Content-Type: application/json

{
    "firstName":"David",
    "lastName":"Doe",
    "email":"muriithikiamad1@gmail.com" ,
    "role":"customer",    
    "phoneNumber":"03655644567",
    "password":"password12344"
}


###
DELETE  http://localhost:4500/users/deactivateUser/78386d78-0b45-47b4-9ae0-13a26052f6b2
Content-Type: application/json

###
GET  http://localhost:4500/users/allCustomers
Content-Type: application/json


###
GET  http://localhost:4500/users/customer/78386d78-0b45-47b4-9ae0-13a26052f6b2
Content-Type: application/json

###
###
GET  http://localhost:4500/users/allCouriers
Content-Type: application/json


###
GET  http://localhost:4500/users/courier
Content-Type: application/json


###    Inventory Routes
POST http://localhost:4500/inventory/addProduct
Content-Type: application/json

{
    "image":"wertyuiertyuidfgh",
    "productName":"Kales",
    "description":"Green leafy vegetables",
    "category":"Vegetables",
    "quantity":"5",
    "currentPrice":"4", 
    "formerPrice":"4"
}


###


GET  http://localhost:4500/inventory/allProducts
Content-Type: application/json


###
GET  http://localhost:4500/inventory/product/f0619109-b60b-4714-93ed-fc07895ec3da
Content-Type: application/json


###
DELETE   http://localhost:4500/inventory/deleteProduct/f0619109-b60b-4714-93ed-fc07895ec3da
Content-Type: application/json


### Cart Routes
POST http://localhost:4500/cart/addToCart
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ODM4NmQ3OC0wYjQ1LTQ3YjQtOWFlMC0xM2EyNjA1MmY2YjIiLCJmaXJzdE5hbWUiOiJEYXZpZCIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJtdXJpaXRoaWtpYW1hZDErNDIzQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInBob25lTnVtYmVyIjoiMDM2NTU2NDQ1NjciLCJyZWdpc3RlckRhdGUiOiIyMDI0LTA0LTI0VDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3MTQxMTc0MDksImV4cCI6MTcxNDM3NjYwOX0.Su08LNbdg-99OihBahfGj8p8asl5UQZGXJ2lpjbsYWs

{
    "productId":"f0619109-b60b-4714-93ed-fc07895ec3da",
    "userId":"78386d78-0b45-47b4-9ae0-13a26052f6b2",
    "quantity":"5"
}


### 
DELETE  http://localhost:4500/cart/removeItemFromCart/f0619109-b60b-4714-93ed-fc07895ec3da
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ODM4NmQ3OC0wYjQ1LTQ3YjQtOWFlMC0xM2EyNjA1MmY2YjIiLCJmaXJzdE5hbWUiOiJEYXZpZCIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJtdXJpaXRoaWtpYW1hZDErNDIzQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInBob25lTnVtYmVyIjoiMDM2NTU2NDQ1NjciLCJyZWdpc3RlckRhdGUiOiIyMDI0LTA0LTI0VDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3MTQxMTc0MDksImV4cCI6MTcxNDM3NjYwOX0.Su08LNbdg-99OihBahfGj8p8asl5UQZGXJ2lpjbsYWs



