POST  http://localhost:4500/users/register
Content-Type: application/json

{
    "firstName":"David",
    "lastName":"Doe",
    "email":"muriithikiamad1@gmail.com" ,
    "role":"customer",    
    "phoneNumber":"03655644567",
    "password":"password12344"
}


###
DELETE  http://localhost:4500/users/deactivateUser/78386d78-0b45-47b4-9ae0-13a26052f6b2
Content-Type: application/json

###
GET  http://localhost:4500/users/allCustomers
Content-Type: application/json


###
GET  http://localhost:4500/users/customer/78386d78-0b45-47b4-9ae0-13a26052f6b2
Content-Type: application/json

###
###
GET  http://localhost:4500/users/allCouriers
Content-Type: application/json


###
GET  http://localhost:4500/users/courier
Content-Type: application/json


###    Inventory Routes
POST http://localhost:4500/inventory/addProduct
Content-Type: application/json

{
    "image":"wertyuiertyuidfgh",
    "productName":"Kales",
    "description":"Green leafy vegetables",
    "category":"Vegetables",
    "quantity":"5",
    "currentPrice":"4", 
    "formerPrice":"4"
}


