POST http://localhost:4500/auth/login 
Content-Type: application/json

{
    "email":"muriithikiamad1+423@gmail.com",
    "password":"password12344"
}

###
GET http://localhost:4500/auth/checkUserDetails
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ODM4NmQ3OC0wYjQ1LTQ3YjQtOWFlMC0xM2EyNjA1MmY2YjIiLCJmaXJzdE5hbWUiOiJEYXZpZCIsImxhc3ROYW1lIjoiRG9lIiwiZW1haWwiOiJtdXJpaXRoaWtpYW1hZDErNDIzQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsInBob25lTnVtYmVyIjoiMDM2NTU2NDQ1NjciLCJyZWdpc3RlckRhdGUiOiIyMDI0LTA0LTI0VDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3MTM5MzkyMzUsImV4cCI6MTcxNDE5ODQzNX0.8D4P90M0Q-WFMLAOS5ftlFDKFSivVN-4va0w8l10--E